
// Enums for Role-Based Access Control (RBAC)
export enum UserRole {
  ADMIN = 'ADMIN',
  CONTADOR = 'CONTADOR',
  AUDITOR = 'AUDITOR',
  VENDEDOR = 'VENDEDOR',
  CLIENTE = 'CLIENTE',
}

export type ProductGender = 'HOMBRE' | 'MUJER' | 'NIÑA' | 'NIÑO' | 'UNISEX';

// User Entity
export interface User {
  id: string; // UUID
  email: string;
  full_name: string;
  role: UserRole;
  is_active: boolean; // New Field for Soft Delete
  created_at: string;
}

// Customer Entity (CRM)
export interface Customer {
  id: string;
  name: string; // Changed from full_name to match DB
  nit?: string; // Tax ID / DNI / CI
  phone?: string;
  email?: string;
  address?: string;
  notes?: string; // Added to match DB
  total_purchases?: number; // Added to match DB
  created_at?: string;
  updated_at?: string;
}

// Category Entity (Nueva Tabla Maestra)
export interface Category {
  id: string;
  name: string;
}

// Payment Method Entity (Control Interno)
export type PaymentMethodType = 'CASH' | 'CARD' | 'TRANSFER' | 'OTHER';

export interface PaymentMethod {
  id: string;
  name: string; // Ej: "Efectivo Caja 1", "POS BAC", "Cuenta Monetaria BI"
  type: PaymentMethodType;
  is_active: boolean;
}

// Product Entity (Master Data - ADN del producto)
export interface Product {
  id: string; // UUID (IdProducto)
  sku: string; // Identificador único comercial (Barcode)
  name: string; // Nombre del Producto
  brand: string; // Marca
  description?: string; // Descripción
  category_id?: string; // FK to Category
  category_name?: string; // Helper for UI
  min_stock?: number; // Minimo requerido (Alerta de Reorden)

  price: number; // Precio Actual de Venta
  cost?: number; // Costo del producto
  stock_level: number; // Stock Actual

  color?: string; // New: Color
  gender?: string; // New: Género

  image_url?: string; // Imagen
  is_active?: boolean; // Si está activo

  // Auditoría
  created_at?: string; // Fecha de registro
  updated_at?: string; // Fecha de actualización
}

// Sale Header (Maestro/Documento)
export interface SaleHeader {
  id: string; // UUID
  user_id: string; // Trazabilidad: Quién hizo la venta

  customer_id?: string; // FK Optional to Customer Table
  customer_name: string | null; // Snapshot (Redundancy for invoices)

  total_amount: number;
  subtotal?: number;
  discount?: number;
  tax?: number;
  status: 'PENDING' | 'COMPLETED' | 'CANCELLED';
  payment_method_id: string; // FK PaymentMethod
  payment_method_snapshot: string; // Historical name (e.g., if "POS BAC" is renamed later)
  created_at: string;
}

// Sale Detail (Detalle/Líneas)
export interface SaleDetail {
  id: string; // UUID
  sale_id: string; // FK to SaleHeader
  product_id: string; // FK to Product
  quantity: number;
  unit_price: number; // Snapshot of price at moment of sale
  subtotal: number;
}

// --- INVENTORY MODULE ENTITIES ---

export type MovementType = 'IN' | 'OUT' | 'ADJUSTMENT'; // ENTRADA (Compra) | SALIDA (Merma) | AJUSTE (Auditoría)

// Inventory Header (Cabecera de Movimiento)
export interface InventoryMovementHeader {
  id: string;
  user_id: string; // Trazabilidad: Responsable del movimiento
  date: string;
  type: MovementType;
  reason: string; // Glosa / Motivo
  reference_doc?: string; // Nro Factura Proveedor, etc.
  total_cost_impact: number; // Suma financiera del movimiento
  audit_session_id?: string; // Optional: Link to Audit Session if generated by audit
}

// Inventory Detail (Detalle de Movimiento)
export interface InventoryMovementDetail {
  id: string;
  movement_id: string; // FK Header
  product_id: string; // FK Product
  quantity: number;
  unit_cost: number; // Costo de adquisición real en este momento
  new_price?: number; // Precio de Venta Sugerido/Actualizado (Solo en entradas)
  total_cost: number;
}

// --- EXPENSES MODULE ENTITIES ---
// Expense Account Management
export interface ExpenseAccountModel {
  id: string;
  name: string;
  description?: string;
  created_at?: string;
}

export interface ExpenseSubAccountModel {
  id: string;
  account_id: string;
  name: string;
  created_at?: string;
}

export type ExpensePaymentType = 'CONTADO' | 'CREDITO';
// Relaxed to string to allow dynamic accounts from DB
export type ExpenseAccount = string;
export type ExpenseStatus = 'PAID' | 'PENDING' | 'PARTIAL';

// Supplier Entity (Proveedores)
export interface Supplier {
  id: string;
  name: string;
  contact_name?: string;
  phone?: string;
  email?: string;
  tax_id?: string;
  address?: string;
  notes?: string;
  created_at: string;
}

// Expense Header (La Factura/Documento)
export interface Expense {
  id: string;
  date: string; // Fecha de emisión
  supplier_id?: string; // FK Optional
  supplier: string; // Proveedor Snapshot
  account: ExpenseAccount;
  sub_account: string;
  total: number;
  payment_type: ExpensePaymentType;

  // Debt Management Fields
  remaining_amount: number; // Saldo pendiente
  status: ExpenseStatus; // Estado de la deuda

  image_url?: string;
  user_id: string;
  created_at: string;
}

// Expense Payment (El Abono - Trazabilidad de CxP)
export interface ExpensePayment {
  id: string;
  expense_id: string; // FK Expense
  amount: number; // Monto abonado
  date: string; // Fecha del pago
  note?: string; // Referencia bancaria, cheque, etc.
  user_id: string; // Quien registró el pago
}

// Helper type for cart management (frontend only)
export interface CartItem extends Product {
  quantity: number;
  discountPerUnit?: number; // Optional discount in currency amount (not percentage)
}

// --- AUDIT SESSION MODULE ---
export interface AuditSession {
  id: string; // UUID
  user_id: string; // Auditor
  start_date: string;
  end_date?: string; // Null if active
  status: 'OPEN' | 'CLOSED' | 'CANCELLED';
  type: 'PARTIAL' | 'FULL'; // Partial: Only adjusted items. Full: Uncounted items set to 0. (Only Partial implemented for now)

  // Snapshots for Reporting
  summary_total_system_value: number; // Valor total teórico antes del ajuste
  summary_total_physical_value: number; // Valor total contado
  summary_net_variance: number; // Diferencia Total $ (Positiva o Negativa)

  note?: string;
}
